name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: make build

    - name: Test
      run: make test
      
    # Test if anything changed (maining a generator or manifest changed
    - name: git diff
      run: git diff --no-ext-diff --quiet --exit-code
